/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class reverse */

#ifndef _Included_reverse
#define _Included_reverse
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     reverse
 * Method:    reversefunc
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_reverse_reversefunc
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
