/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class factorial */

#ifndef _Included_factorial
#define _Included_factorial
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     factorial
 * Method:    fact
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_factorial_fact
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
