/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class daysofweek */

#ifndef _Included_daysofweek
#define _Included_daysofweek
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     daysofweek
 * Method:    returndays
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_daysofweek_returndays
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
