/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fibonacci */

#ifndef _Included_fibonacci
#define _Included_fibonacci
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fibonacci
 * Method:    returnfibo
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_fibonacci_returnfibo
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
